"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const contact_routes_1 = require("./components/contact/contact.routes");
const home_routes_1 = require("./components/home/home.routes");
const check_routes_1 = require("./components/check/check.routes");
const authorize_routes_1 = require("./components/authorize/authorize.routes");
const approve_routes_1 = require("./components/approve/approve.routes");
const router = express_1.Router();
router.use("/contact", contact_routes_1.default);
router.use("/check", check_routes_1.default);
router.use("/authorize", authorize_routes_1.default);
router.use("/approve", approve_routes_1.default);
router.use("", home_routes_1.default);
exports.default = router;
