"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const helpers_1 = require("../server/helpers");
const contact_controller_1 = require("./components/contact/contact.controller");
const check_controller_1 = require("./components/check/check.controller");
const authorize_controller_1 = require("./components/authorize/authorize.controller");
const approve_controller_1 = require("./components/approve/approve.controller");
const token_controller_1 = require("./components/token/token.controller");
const userinfo_controller_1 = require("./components/userinfo/userinfo.controller");
const homepage_controller_1 = require("./components/homepage/homepage.controller");
const home_controller_1 = require("./components/home/home.controller");
const router = express_1.Router();
router.get("/contact", contact_controller_1.default.getContactPage);
router.get("/check", check_controller_1.default.getCheckPage);
router.get("/authorize", authorize_controller_1.default.getAuthorize);
router.post("/approve", approve_controller_1.default.approve);
router.post("/token", token_controller_1.default.getToken);
router.get("/userinfo", helpers_1.getAccessToken, helpers_1.requireAccessToken, userinfo_controller_1.default.getUserinfo);
router.post("/userinfo", helpers_1.getAccessToken, helpers_1.requireAccessToken, userinfo_controller_1.default.getUserinfo);
router.get("/homepage", homepage_controller_1.default.getHomepage);
router.get("/", home_controller_1.default.getHomePage);
exports.default = router;
